<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Feed extends \Application\Entity\Feed implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\Feed' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Feed' . "\0" . 'programId', '' . "\0" . 'Application\\Entity\\Feed' . "\0" . 'productCount', '' . "\0" . 'Application\\Entity\\Feed' . "\0" . 'file', '' . "\0" . 'Application\\Entity\\Feed' . "\0" . 'feedCategory', '' . "\0" . 'Application\\Entity\\Feed' . "\0" . 'feedProductProperty'];
        }

        return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\Feed' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Feed' . "\0" . 'programId', '' . "\0" . 'Application\\Entity\\Feed' . "\0" . 'productCount', '' . "\0" . 'Application\\Entity\\Feed' . "\0" . 'file', '' . "\0" . 'Application\\Entity\\Feed' . "\0" . 'feedCategory', '' . "\0" . 'Application\\Entity\\Feed' . "\0" . 'feedProductProperty'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Feed $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setProgramId($programId = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProgramId', [$programId]);

        return parent::setProgramId($programId);
    }

    /**
     * {@inheritDoc}
     */
    public function getProgramId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProgramId', []);

        return parent::getProgramId();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductCount($productCount = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductCount', [$productCount]);

        return parent::setProductCount($productCount);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductCount', []);

        return parent::getProductCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setFile($file)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFile', [$file]);

        return parent::setFile($file);
    }

    /**
     * {@inheritDoc}
     */
    public function getFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFile', []);

        return parent::getFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setFeedCategory(\Application\Entity\FeedCategory $feedCategory = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFeedCategory', [$feedCategory]);

        return parent::setFeedCategory($feedCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function getFeedCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFeedCategory', []);

        return parent::getFeedCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function addFeedProductProperty(\Application\Entity\FeedProductProperty $feedProductProperty)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFeedProductProperty', [$feedProductProperty]);

        return parent::addFeedProductProperty($feedProductProperty);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFeedProductProperty(\Application\Entity\FeedProductProperty $feedProductProperty)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFeedProductProperty', [$feedProductProperty]);

        return parent::removeFeedProductProperty($feedProductProperty);
    }

    /**
     * {@inheritDoc}
     */
    public function getFeedProductProperty()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFeedProductProperty', []);

        return parent::getFeedProductProperty();
    }

}
