<?php
$this->form->prepare();
?>

<div class="content-wrapper">
	<section class="content-header">
		<h1>Object</h1>
		<ol class="breadcrumb">
			<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		</ol>
	</section>

	<section class="content">
		<div class="row">
			<div class="col-md-12">
				<div class="box box-info">
					<div class="box-header with-border">
						<h3 class="box-title">Programs</h3>
						<div class="box-tools pull-right">
							<button type="button" class="btn btn-box-tool"
								data-widget="collapse">
								<i class="fa fa-minus"></i>
							</button>
							<button type="button" class="btn btn-box-tool"
								data-widget="remove">
								<i class="fa fa-times"></i>
							</button>
						</div>
					</div>
					<div class="box-body">
        				<?php
            echo $this->form()->openTag($this->form);
            echo '
                <div class="form-group">
                    ' . $this->formselect($this->form->get('din')) . '
                </div>
                <div class="form-group">
                    ' . $this->forminput($this->form->get('name')) . '
                </div>
            ';
            ?>
                    </div>
					<div class="box-footer">
						<button type="submit" class="btn btn-primary">Submit</button>
					</div>
					<?php echo $this->form()->closeTag(); ?>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<div class="box box-info">
					<div class="box-header with-border">
						<h3 class="box-title">Programs</h3>

						<div class="box-tools pull-right">
							<button type="button" class="btn btn-box-tool"
								data-widget="collapse">
								<i class="fa fa-minus"></i>
							</button>
							<button type="button" class="btn btn-box-tool"
								data-widget="remove">
								<i class="fa fa-times"></i>
							</button>
						</div>
					</div>
					<!-- /.box-header -->
					<div class="box-body">
						<div class="table-responsive">
							<table
								class="table table-striped table-hover table-condensed no-margin">
								<thead>
									<tr>
										<th></th>
										<th>METRIC</th>
										<th>STEEL LENGTH</th>
										<th>QUALITY</th>
										<th></th>
									</tr>
								</thead>
								<tbody>
    				<?php
        foreach ($this->bolt->getBoltSize() as $boltSize) {
            echo '
                            <tr>
                                <td></td>
        						<td>' . $boltSize->getMetric() . '</td>
        						<td>' . $boltSize->getSteelLength() . '</td>
                                <td><a href="#" class="quality" data-type="text" data-url="/admin/bolt/edit-size/' . $boltSize->getId() . '" data-pk="' . $boltSize->getId() . '">' . $boltSize->getQuality() . '</a></td>
                                <td>
<div class="btn-group">
      <button type="button" class="btn btn-xs btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Choose action <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li><a href="javascript:" onclick="copy();" data-toggle="modal" data-target="#modal-copy">Copy</a></li>
        <li role="separator" class="divider"></li>
        <li><a style="color: red;" href="#">Disable</a></li>
      </ul>
    </div>
                                </td>
        					</tr>
                        ';
        }
        ?>
				</tbody>
							</table>
						</div>
					</div>
					<div class="box-footer clearfix">
						<a href="/admin/object/create/1"
							class="btn btn-sm btn-info btn-flat pull-left">New record</a> <a
							href="javascript:void(0)"
							class="btn btn-sm btn-default btn-flat pull-right">View all</a>
					</div>
				</div>
			</div>
		</div>
	</section>
</div>

<?php
$this->inlinescript()->captureStart();
echo <<<JS
    $(document).ready(function() {
        $('table').DataTable({
            columnDefs: [ {
                orderable: false,
                className: 'select-checkbox',
                targets:   0
            } ],
            select: {
                style:    'os',
                selector: 'td:first-child'
            },
            order: [[ 1, 'asc' ]]
        });

//         $.fn.editable.defaults.mode = 'inline';
        $('.quality').editable();
    });
JS;
$this->inlinescript()->captureEnd();