<div class="content-wrapper">
	<section class="content-header">
		<h1>Object</h1>
		<ol class="breadcrumb">
			<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		</ol>
	</section>

	<section class="content">
		<div class="row">
			<div class="col-md-12">
				<div class="box box-info">
					<div class="box-header with-border">
						<h3 class="box-title">Programs</h3>

						<div class="box-tools pull-right">
							<button type="button" class="btn btn-box-tool"
								data-widget="collapse">
								<i class="fa fa-minus"></i>
							</button>
							<button type="button" class="btn btn-box-tool"
								data-widget="remove">
								<i class="fa fa-times"></i>
							</button>
						</div>
					</div>
					<!-- /.box-header -->
					<div class="box-body">
						<div class="table-responsive">
							<table
								class="table table-striped table-hover table-condensed no-margin">
								<thead>
									<tr>
										<th>DIN</th>
										<th>Name</th>
										<th></th>
									</tr>
								</thead>
								<tbody>
    				<?php
        foreach ($this->bolts as $bolt) {
            echo '
                            <tr>
        						<td>' . $bolt->getDin()->getName() . '</td>
        						<td>' . $bolt->getName() . '</td>
                                <td>
<div class="btn-group">
      <button type="button" class="btn btn-xs btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Choose action <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li><a href="/admin/bolt/edit/' . $bolt->getId() . '">Edit</a></li>
        <li><a href="javascript:" onclick="load(' . $bolt->getId() . ');" data-toggle="modal" data-target="#modal-default">Add size(s)</a></li>
        <li role="separator" class="divider"></li>
        <li><a style="color: red;" href="#">Disable</a></li>
      </ul>
    </div>
                                </td>
        					</tr>
                        ';
        }
        ?>
				</tbody>
							</table>
						</div>
					</div>
					<div class="box-footer clearfix">
						<a href="/admin/bolt/create"
							class="btn btn-sm btn-info btn-flat pull-left">New record</a> <a
							href="javascript:void(0)"
							class="btn btn-sm btn-default btn-flat pull-right">View all</a>
					</div>
				</div>
			</div>
		</div>
	</section>
</div>

<div class="modal fade" id="modal-default"></div>

<?php
$this->inlinescript()->captureStart();
echo <<<JS

    function load(boltId) {
        $('#modal-default').load('/admin/bolt/add-size/' + boltId + '', function() {
        });
    }

    $(document).ready(function() {
        $('.table').DataTable();
    });
JS;
$this->inlinescript()->captureEnd();