<div class="content-wrapper">
	<section class="content-header">
		<h1>Productfeeds</h1>
		<ol class="breadcrumb">
			<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		</ol>
	</section>
	<section class="content">
		<div class="box">
			<div class="box-body">
				<table class="table table-striped table-hover table-condensed no-margin">
					<thead>
						<tr>
							<th>ID</th>
							<th>Program ID</th>
							<th>Product count</th>
						</tr>
					</thead>
					<tbody>
                        <?php
                        if (! empty($this->feeds) && is_array($this->feeds)) {
                            foreach ($this->feeds as $feed) {
                                echo '
                                    <tr>
                                        <td>' . $feed->getId() . '</td>
                                        <td>' . $feed->getProgramId() . '</td>
                                        <td>' . $feed->getProductCount() . '</td>
                                    </tr>
                                ';
                            }
                        }
                        ?>
                    </tbody>
					<tfoot>
						<tr>
							<th>ID</th>
							<th>Program ID</th>
							<th>Product count</th>
						</tr>
					</tfoot>
				</table>
			</div>
		</div>
	</section>
</div>

<?php
$this->inlinescript()->captureStart();
echo <<<JS
    $(document).ready(function(){
       $('table').DataTable();
    })
JS;
$this->inlinescript()->captureEnd();