<?php
use Zend\Form\Element;
?>
<div class="content-wrapper">
	<section class="content-header">
		<h1>Productfeeds</h1>
		<ol class="breadcrumb">
			<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		</ol>
	</section>
	<section class="content">
		<div class="box">
			<div class="box-body">
				<table
					class="table table-striped table-hover table-condensed no-margin">
					<thead>
						<tr>
							<th>ID</th>
							<th>Name</th>
							<th>Assignment status</th>
							<th>Status</th>
							<th><?php echo $this->translate('Locked'); ?></th>
						</tr>
					</thead>
					<tbody>
                        <?php
                        foreach ($this->feed->getFeedProductProperty() as $property) {
                            $dbTable = $property->getListObject();
                            $dbTableProperty = $property->getDbTableProperty();
                            
                            $buttonText = 'Not assigned';
                            $buttonClass = 'btn btn-danger btn-xs';
                            
                            if ($dbTable !== null && $dbTableProperty !== null) {
                                $buttonText = 'Assigned';
                                $buttonClass = 'btn btn-success btn-xs';
                            }
                            
                            $attributes = null;
                            if ($this->isAllowed('feed', 'feed-link-properties')) {
                                $buttonClass .= ' load';
                                $attributes = 'data-href="/admin/feed/link-properties/' . $this->feed->getId() . '-' . $property->getId() . '" data-toggle="modal" data-target="#myModal"';
                            }
                            
                            $active = new Element\Checkbox();
                            $active->setName('active')->setValue($property->getActive());
                            
                            $locked = new Element\Checkbox();
                            $locked->setName('locked')->setValue($property->getLocked());
                            
                            echo '
                                <tr>
                                    <td>' . $property->getId() . '</td>
                                    <td>' . $property->getName() . '</td>
                                    <td>
                                        ' . ($property->getLocked() == 0 ? '<a class="' . $buttonClass . '" ' . $attributes . '>' . $buttonText . '</a>' : null) . '
                                    </td>
                                    <td>' . $this->formCheckbox($active) . '</td>
                                    <td>' . $this->formCheckbox($locked) . '</td>
                                </tr>
                            ';
                        }
                        ?>
                    </tbody>
					<tfoot>
						<tr>
							<th>ID</th>
							<th>Name</th>
							<th>Assignment status</th>
							<th>Status</th>
							<th><?php echo $this->translate('Locked'); ?></th>
						</tr>
					</tfoot>
				</table>
			</div>
		</div>
	</section>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog"
	aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content"></div>
	</div>
</div>

<?php
$this->inlinescript()->captureStart();
echo <<<JS
    $(document).ready(function() {
        $('a.load').click(function() {
            console.log('123');
			$('.modal-content').load($(this).data('href'));
        });

        $('table').DataTable();
    });
JS;
$this->inlinescript()->captureEnd();