<div class="content-wrapper">
	<section class="content-header">
		<h1>Productfeeds</h1>
		<ol class="breadcrumb">
			<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		</ol>
	</section>
	<section class="content">
		<div class="box">
			<div class="box-body">
				<table
					class="table table-striped table-hover table-condensed no-margin">
					<thead>
						<tr>
							<th>ID</th>
							<th>Name</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
                        <?php
                        foreach ($this->feed->getFeedProductProperty() as $property) {
                            echo '
                                <tr>
                                    <td>' . $property->getId() . '</td>
                                    <td>' . $property->getName() . '</td>
                                    <td>
                                        <button type="button" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#myModal">
                                            Assign
                                        </button>
                                    </td>
                                </tr>
                            ';
                        }
                        ?>
                    </tbody>
					<tfoot>
						<tr>
							<th>ID</th>
							<th>Name</th>
							<th></th>
						</tr>
					</tfoot>
				</table>
			</div>
		</div>
	</section>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog"
	aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"
					aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				<h4 class="modal-title" id="myModalLabel">Modal title</h4>
			</div>
			<div class="modal-body">
				<form class="form-horizontal">
					<div class="form-group">
						<label for="inputEmail3" class="col-sm-2 control-label">Table</label>
						<div class="col-sm-10">
							<select class="form-control"><option value="brand">Brand (brand)</option></select>
						</div>
					</div>
					<div class="form-group">
						<label for="inputPassword3" class="col-sm-2 control-label">Property</label>
						<div class="col-sm-10">
							<select class="form-control"><option value="name">name</option></select>
						</div>
					</div>
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				<button type="button" class="btn btn-primary">Save changes</button>
			</div>
		</div>
	</div>
</div>

<?php
$this->inlinescript()->captureStart();
echo <<<JS
    $(document).ready(function(){
       $('table').DataTable();
    })
JS;
$this->inlinescript()->captureEnd();