<div class="content-wrapper">
	<section class="content-header">
		<h1>Accounts</h1>
		<ol class="breadcrumb">
			<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		</ol>
	</section>
	<section class="content">
		<div class="box">
			<div class="box-body">
				<table class="table table-striped table-hover table-condensed no-margin">
					<thead>
						<tr>
							<th></th>
							<th>ID</th>
							<th>First name</th>
							<th>Middle name</th>
							<th>Last name</th>
							<th>E-mail address</th>
						</tr>
					</thead>
					<tbody>
                        <?php
                        if (! empty($this->accounts) && is_array($this->accounts)) {
                            foreach ($this->accounts as $account) {
                                echo '
                                    <tr>
                                        <td class="text-left">
                                            <div class="btn-group">
                                                <button type="button" class="btn btn-xs btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    Choose action <span class="caret"></span>
                                                </button>
                                                <ul class="dropdown-menu">
                                                    ' . ($this->isAllowed('account', 'reset-password') ? '<li><a href="javascript:" onclick="location.href = \'/admin/account/reset-password/1\'">Reset password</a></li>' : null) . '
                                                    <li role="separator" class="divider"></li>
                                                    <li><a style="color: red;" href="#">Disable</a></li>
                                                </ul>
                                            </div>
                                        </td>
                                        <td>' . $account->getId() . '</td>
                                        <td>' . ($this->isAllowed('account', 'update-account') ? '<a href="#" id="firstName" class="editable" data-type="text" data-pk="' . $account->getId() . '">' . $account->getFirstName() . '</a>' : $account->getFirstName()) . '</td>
                                        <td>' . ($this->isAllowed('account', 'update-account') ? '<a href="#" id="firstName" class="editable" data-type="text" data-pk="' . $account->getId() . '">' . $account->getMiddleName() . '</a>' : $account->getMiddleName()) . '</td>
                                        <td>' . ($this->isAllowed('account', 'update-account') ? '<a href="#" id="firstName" class="editable" data-type="text" data-pk="' . $account->getId() . '">' . $account->getLastName() . '</a>' : $account->getLastName()) . '</td>
                                        <td>' . ($this->isAllowed('account', 'update-account') ? '<a href="#" id="firstName" class="editable" data-type="text" data-pk="' . $account->getId() . '">' . $account->getEmail() . '</a>' : $account->getEmail()) . '</td>
                                    </tr>
                                ';
                            }
                        }
                        ?>
                    </tbody>
					<tfoot>
						<tr>
							<th></th>
							<th>ID</th>
							<th>First name</th>
							<th>Middle name</th>
							<th>Last name</th>
							<th>E-mail address</th>
						</tr>
					</tfoot>
				</table>
			</div>
		</div>
	</section>
</div>

<?php
$this->inlinescript()->captureStart();
echo <<<JS
    $(document).ready(function(){
       $('table').DataTable();

        $.fn.editable.defaults.mode = 'inline';

        $('.editable').editable();
    })
JS;
$this->inlinescript()->captureEnd();