<div class="content-wrapper">
	<section class="content-header">
		<h1>Product</h1>
		<ol class="breadcrumb">
			<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		</ol>
	</section>

	<section class="content">
		<div class="row">
			<div class="col-md-12">
				<div class="nav-tabs-custom">
					<ul class="nav nav-tabs">
						<li><a href="javascript:"
							data-href="/admin/product/info/<?php echo $this->productId; ?>"
							data-toggle="tab">Product info</a></li>
						<li><a href="javascript:"
							data-href="/admin/product/images/<?php echo $this->productId; ?>"
							data-toggle="tab">Images</a></li>
						<li><a href="javascript:"
							data-href="/admin/product/seo/<?php echo $this->productId; ?>"
							data-toggle="tab">SEO</a></li>
						<li><a href="javascript:"
							data-href="/admin/product/history/<?php echo $this->productId; ?>"
							data-toggle="tab">History</a></li>
					</ul>
					<div class="tab-content">
						<div class="tab-pane active" id="tab-content"></div>
					</div>
				</div>

				<div class="box box-primary"></div>
			</div>
		</div>
	</section>
</div>

<?php
$this->inlinescript()->captureStart();
echo <<<JS
	$(document).ready(function() {
		$('.nav-tabs a').click(function() {
			$('#tab-content').load($(this).data('href'), function(response, status, xhr) {
				console.log(status);
				console.log(response);
				console.log(xhr);
			});
		});

		$('#imageTable').DataTable();

		$('.select2').select2();
	});
JS;
$this->inlinescript()->captureEnd();
