<div class="content-wrapper">
	<section class="content-header">
		<h1>To Do</h1>
		<ol class="breadcrumb">
			<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		</ol>
	</section>
	<section class="content">
		<div class="row">
			<div class="col-md-8">
				<?php if($this->isAllowed('todo', 'todo-view-work-items')) : ?>
				<div class="box box-info">
					<div class="box-header with-border">
						<h3 class="box-title">Work items</h3>

						<div class="box-tools pull-right">
							<button type="button" class="btn btn-box-tool"
								data-widget="collapse">
								<i class="fa fa-minus"></i>
							</button>
							<button type="button" class="btn btn-box-tool"
								data-widget="remove">
								<i class="fa fa-times"></i>
							</button>
						</div>
					</div>
					<!-- /.box-header -->
					<div class="box-body">
						<table class="table table-striped table-hover table-condensed no-margin table-responsive">
							<thead>
    							<tr>
    								<th>ID</th>
    								<th></th>
    								<th>Description</th>
    								<th>Status</th>
    								<th>Creation date</th>
    							</tr>
							</thead>
    						<tbody>
    							<?php
    							if (! empty($this->todos) && is_array($this->todos)) {
    							    foreach ($this->todos as $todo) {
    							        echo '
                                            <tr>
                								<td>' . $todo->getId() . '</td>
                                                <td class="text-left">
                                                    <div class="btn-group">
                                                        <button type="button" class="btn btn-xs btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                            Choose action <span class="caret"></span>
                                                        </button>
                                                        <ul class="dropdown-menu">
                                                            ' . ($this->isAllowed('todo', 'todo-close') ? '<li><a href="javascript:" onclick="location.href = \'/admin/todo/update-ajax/' . $todo->getId() . '\'">Close</a></li>' : null) . '
                                                            <li role="separator" class="divider"></li>
                                                            <li><a style="color: red;" href="#">Delete</a></li>
                                                        </ul>
                                                    </div>
                                                </td>
                								<td>' . $todo->getDescription() . '</td>
                								<td>' . $todo->getStatus() . '</td>
                								<td>' . $todo->getCreationDate()->format('d-m-Y h:i:s') . '</td>
                							</tr>
                                        ';
    							    }
    							}
    							?>
    						</tbody>
    						<tfoot>
    							<tr>
    								<th>ID</th>
    								<th></th>
    								<th>Description</th>
    								<th>Status</th>
    								<th>Creation date</th>
    							</tr>
							</tfoot>
						</table>
					</div>
					<!-- /.box-body -->
					<div class="box-footer clearfix">
						<a href="javascript:void(0)"
							class="btn btn-sm btn-info btn-flat pull-left">Place new work item</a>
						<a href="javascript:void(0)"
							class="btn btn-sm btn-default btn-flat pull-right">View All</a>
					</div>
					<!-- /.box-footer -->
				</div>
				<?php endif; ?>
				<?php if($this->isAllowed('todo', 'todo-view-latest-reviews')) : ?>
				<div class="box box-info">
					<div class="box-header with-border">
						<h3 class="box-title">Latest reviews</h3>

						<div class="box-tools pull-right">
							<button type="button" class="btn btn-box-tool"
								data-widget="collapse">
								<i class="fa fa-minus"></i>
							</button>
							<button type="button" class="btn btn-box-tool"
								data-widget="remove">
								<i class="fa fa-times"></i>
							</button>
						</div>
					</div>
					<!-- /.box-header -->
					<div class="box-body">
					</div>
					<!-- /.box-body -->
					<div class="box-footer clearfix">
						<a href="javascript:void(0)"
							class="btn btn-sm btn-default btn-flat pull-right">View All</a>
					</div>
					<!-- /.box-footer -->
				</div>
				<?php endif; ?>
			</div>
			<div class="col-md-4">
				<div class="info-box bg-yellow">
					<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>

					<div class="info-box-content">
						<span class="info-box-text">SEO</span> <span
							class="info-box-number">5,200</span>

						<div class="progress">
							<div class="progress-bar" style="width: 50%"></div>
						</div>
						<span class="progress-description">
							<button class="btn btn-xs btn-warning">View all</button>
						</span>
					</div>
				</div>
				<div class="info-box bg-green">
					<span class="info-box-icon"><i class="ion ion-ios-heart-outline"></i></span>

					<div class="info-box-content">
						<span class="info-box-text">Mentions</span> <span
							class="info-box-number">92,050</span>

						<div class="progress">
							<div class="progress-bar" style="width: 20%"></div>
						</div>
						<span class="progress-description"> 20% Increase in 30 Days </span>
					</div>
				</div>
				<div class="info-box bg-red">
					<span class="info-box-icon"><i
						class="ion ion-ios-cloud-download-outline"></i></span>

					<div class="info-box-content">
						<span class="info-box-text">Downloads</span> <span
							class="info-box-number">114,381</span>

						<div class="progress">
							<div class="progress-bar" style="width: 70%"></div>
						</div>
						<span class="progress-description"> 70% Increase in 30 Days </span>
					</div>
				</div>
				<div class="info-box bg-aqua">
					<span class="info-box-icon"><i class="ion-ios-chatbubble-outline"></i></span>

					<div class="info-box-content">
						<span class="info-box-text">Direct Messages</span> <span
							class="info-box-number">163,921</span>

						<div class="progress">
							<div class="progress-bar" style="width: 40%"></div>
						</div>
						<span class="progress-description"> 40% Increase in 30 Days </span>
					</div>
				</div>
			</div>
		</div>
	</section>
</div>

<?php
$this->inlinescript()->captureStart();
echo <<<JS
    $(document).ready(function(){
       $('table').DataTable();
    })
JS;
$this->inlinescript()->captureEnd();