<ul class="timeline">
	<li class="time-label"><span class="bg-red"> <?php echo $this->product->getCreationDate()->format('d-m-Y'); ?> </span></li>
	<li><i class="fa fa-envelope bg-blue"></i>

		<div class="timeline-item">
			<span class="time"><i class="fa fa-clock-o"></i> <?php echo $this->product->getCreationDate()->format('H:i'); ?></span>

			<h3 class="timeline-header">
				<a href="#"><?php echo $this->product->getCreatedBy(); ?></a>
			</h3>

			<div class="timeline-body">Product created.</div>
		</div></li>
</ul>