<ul class="timeline">

	<!-- timeline time label -->
	<li class="time-label"><span class="bg-red"> 29 Sep. 2017 </span></li>
	<!-- /.timeline-label -->

	<!-- timeline item -->
	<li>
		<!-- timeline icon --> <i class="fa fa-envelope bg-blue"></i>
		<div class="timeline-item">
			<span class="time"><i class="fa fa-clock-o"></i> 12:05</span>

			<h3 class="timeline-header">
				<a href="#">System message</a>
			</h3>

			<div class="timeline-body">Product created.</div>
		</div>
	</li>
	<!-- END timeline item -->
</ul>