<?php
    $productImageCollection = $this->productEntity->getProductImage();
    if (! $productImageCollection->isEmpty()) {
        echo '
									<table id="imageTable" class="table table-bordered table-hover">
										<thead>
											<tr>
												<td>Image</td>
												<td>Alt</td>
												<td>Title</td>
											</tr>
										</thead>
										<tbody>
								';
        foreach ($productImageCollection as $productImageEntity) {
            echo '
										<tr>
											<td><img src="' . $productImageEntity->getName() . '" alt="" title="" style="width: 40px;" /></td>
											<td>X</td>
											<td>X</td>
										</tr>
									';
        }
        echo '
										</tbody>
									</table>
								';
    }
    ?>