<?php
use Zend\Form\View\Helper\FormRow;

$this->form->prepare();
echo $this->form()->openTag($this->form);
?>
<div class="box-body">
	<div class="form-group">
		<label>Naam</label> <?php echo $this->formrow($this->form->get('name')); ?>
	</div>
	<div class="form-group">
		<label>Description</label> <?php echo $this->formrow($this->form->get('description')); ?>
	</div>
	<div class="form-group">
		<label>Url</label> <?php echo $this->formrow($this->form->get('url')); ?>
	</div>
	<div class="form-group">
		<label>Price</label> <?php echo $this->formrow($this->form->get('price')); ?>
	</div>
    <?php
    if ($this->productEntity->getAccommodation()->count() > 0) {
        foreach ($this->form->get('accommodation') as $element) {
            echo '
                <div class="form-group">
            		<label>Name</label> ' . $this->formrow($element->get('name')) . '
            	</div>
            ';
            
            echo '
                <div class="form-group">
            		<label>Latitude</label> ' . $this->formrow($element->get('latitude')) . '
            	</div>
            ';
            
            echo '
                <div class="form-group">
            		<label>Longitude</label> ' . $this->formrow($element->get('longitude')) . '
            	</div>
            ';
        }
    }
    ?>
</div>
<div class="box-footer">
	<input type="submit" class="btn btn-primary" value="Submit" />
</div>
<?php
echo $this->form()->closeTag();

$this->inlinescript()->captureStart();
echo <<<JS
    $(document).ready(function() {
        $('textarea').froalaEditor();
    });
JS;
$this->inlinescript()->captureEnd();

echo $this->inlinescript();