<form role="form">
  <div class="box-body">
    <div class="form-group">
      <label for="">Title</label>
      <input type="text" class="form-control input-xs" id="" placeholder="Enter title">
    </div>
    <div class="form-group">
      <label for="">Meta description</label>
      <textarea class="form-control" rows="3" placeholder="Enter meta description"></textarea>
    </div>
  </div>
  <div class="box-footer">
    <button type="submit" class="btn btn-primary">Submit</button>
  </div>
</form>