<!doctype html>
<html>
	<head lang="en">
		<title></title>
		
		<meta charset="utf-8" />
    	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
		
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous" />
		
		<style type="text/css">
        *
        {
        	padding: 0;
        	margin: 0;
        }
        
        body
        {
        	background-color: transparent;
        }
        
        .container
        {
        	
        }
        
        html
        {
            background: url('http://www.xsjjys.com/data/out/286/WHDQ-514190700.jpg') no-repeat center center fixed; 
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }
        
        .container-fluid
        {
        	background-color: #FFFFFF;
        }
        </style>
	</head>
	<body>
		<div class="container header-small">
			MENU
		</div>
		<div class="container-fluid">
			<div class="container">
				TEST
			</div>
		</div>
		<div class="container">
			<div style="background-color: #FFFFFF; border-radius: 30px; margin: 100px 0; padding: 20px;">
				<div class="row">
    				<div class="col-10">
    					<input type="text" name="" id="" class="form-control" value="" placeholder="Search" />
    				</div>
    				<div class="col-2">
						<button type="button" class="btn btn-success btn-block">Search</button>
    				</div>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-4">Item 1</div>
				<div class="col-lg-4">Item 2</div>
				<div class="col-lg-4">Item 3</div>
			</div>
		</div>
		
		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
	</body>
</html>