<div class="content-wrapper" style="min-height: 916px;">
	<!-- Content Header (Page header) -->
	<section class="content-header">
		<h1>
			Categorie&euml;n
		</h1>
		<ol class="breadcrumb">
			<li><a href="#"><i class="fa fa-dashboard"></i> Admin</a></li>
			<li class="active">categorie&euml;n</li>
		</ol>
	</section>

	<!-- Main content -->
	<section class="content">


		<!-- Main row -->
		<div class="row">
			<?php echo $this->partial('tree.phtml', ['categories' => $this->categories]); ?>
		</div>
	</section>
</div>
