<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
	<!-- Content Header (Page header) -->
	<section class="content-header">
		<h1>
			Data Tables <small>advanced tables</small>
		</h1>
		<ol class="breadcrumb">
			<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
			<li><a href="#">Tables</a></li>
			<li class="active">Data tables</li>
		</ol>
	</section>

	<!-- Main content -->
	<section class="content">
		<div class="row">
			<div class="col-md-6">
				<div class="box box-primary">
						<?php //echo $this->form()->openTag($this->form); ?>
						<div class="box-body">
							<div class="row">
								<div class="col-xs-6">
									<label>Status</label> <?php //echo $this->formrow($this->form->get('name')); ?>
								</div>
							</div>
					</div>
					<div class="box-footer">
						<button type="submit" class="btn btn-primary">Submit</button>
					</div>
					<?php //echo $this->form()->closeTag(); ?>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-12">
				<div class="box">
					<div class="box-header">
						<h3 class="box-title">Hover Data Table</h3>
					</div>
					<!-- /.box-header -->
					<div class="box-body">
						<table id="matching" class="table table-bordered table-hover display responsive no-wrap" width="100%">
							<thead>
								<tr>
									<th>Program ID</th>
									<th>Category</th>
								</tr>
							</thead>
							<tfoot>
								<tr>
									<th>Program ID</th>
									<th>Category</th>
								</tr>
							</tfoot>
						</table>
					</div>
					<!-- /.box-body -->
				</div>
				<!-- /.box -->
			</div>
			<!-- /.col -->
		</div>
		<!-- /.row -->
	</section>
	<!-- /.content -->
</div>
<!-- /.content-wrapper -->

<?php
$this->inlinescript()->captureStart();
echo <<<JS
    $(document).ready(function(){

      $.fn.editable.defaults.mode = 'popup';

      var dataTable = $('#matching').DataTable({
        "processing": true,
        "serverSide": true,
        "ajax": {
            "type": "POST",
            "url": "/admin/category/matching"
        },
        "columns": [
            { "name": "name" },
            { "name": "name" }
        ],
        "initComplete": function(){
          $('.editable').editable();
        }
      });
    });
JS;
$this->inlinescript()->captureEnd();
