<?php
$this->form->prepare();
?>
<div class="content-wrapper">
	<section class="content-header">
		<h1>Product</h1>
		<ol class="breadcrumb">
			<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		</ol>
	</section>

	<section class="content">
		<div class="row">
			<div class="col-md-12">
				<div class="box box-primary">
					<div class="box-body">
    					<?php echo $this->form()->openTag($this->form); ?>
							<label>Naam</label>
							<?php echo $this->formrow($this->form->get('name')); ?>
    					<?php echo $this->form()->closeTag(); ?>
					</div>
				</div>
			</div>
		</div>
	</section>
</div>