<div class="content-wrapper">
	<section class="content-header">
		<h1>Product</h1>
		<ol class="breadcrumb">
			<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		</ol>
	</section>

	<section class="content">
		<div class="row">
			<div class="col-md-12">
				<div class="nav-tabs-custom">
					<ul class="nav nav-tabs">
						<li class="active"><a class="active" href=""
							data-href="/admin/product/info/<?php echo $this->productId; ?>"
							data-toggle="tab">Product info</a></li>
						<li><a href=""
							data-href="/admin/product/properties/<?php echo $this->productId; ?>"
							data-toggle="tab">Properties</a></li>
						<li><a href=""
							data-href="/admin/product/media/<?php echo $this->productId; ?>"
							data-toggle="tab">Media</a></li>
						<li><a href=""
							data-href="/admin/product/seo/<?php echo $this->productId; ?>"
							data-toggle="tab">SEO</a></li>
						<li><a href=""
							data-href="/admin/product/history/<?php echo $this->productId; ?>"
							data-toggle="tab">History</a></li>
						<li><a href=""
							data-href="/admin/product/statistics/<?php echo $this->productId; ?>"
							data-toggle="tab">Statistics</a></li>
						<li><a href=""
							data-href="/admin/product/reviews/<?php echo $this->productId; ?>"
							data-toggle="tab">Reviews</a></li>
						<li><a href=""
							data-href="/admin/product/interests/<?php echo $this->productId; ?>"
							data-toggle="tab">Interests</a></li>
					</ul>
					<div class="tab-content">
						<div class="tab-pane active" id="tab-content"></div>
					</div>
				</div>

				<div class="box box-primary"></div>
			</div>
		</div>
	</section>
</div>

<?php
$this->inlinescript()->captureStart();
echo <<<JS
	$(document).ready(function() {
        $('#tab-content').load($('a.active').data('href'));

		$('.nav-tabs a').click(function(e) {
            e.preventDefault();
			$('#tab-content').load($(this).data('href'));
        });

		$('#imageTable').DataTable();

		$('.select2').select2();
	});
JS;
$this->inlinescript()->captureEnd();
