<div class="content-wrapper">
	<section class="content-header">
		<h1>Productfeeds</h1>
		<ol class="breadcrumb">
			<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		</ol>
	</section>
	<section class="content">
		<div class="box">
			<div class="box-body">
				<table class="table table-striped table-hover table-condensed no-margin">
					<thead>
						<tr>
							<th>Unique ID</th>
							<th>Program ID</th>
							<th>Category</th>
							<th>Name</th>
							<th>Url</th>
							<th></th>
						</tr>
					</thead>
					<tfoot>
						<tr>
							<th>Unique ID</th>
							<th>Program ID</th>
							<th>Category</th>
							<th>Name</th>
							<th>Url</th>
							<th></th>
						</tr>
					</tfoot>
				</table>
			</div>
		</div>
	</section>
</div>

<?php
$this->inlinescript()->captureStart();
echo <<<JS
    $(document).ready(function(){
			$('table').DataTable({
				"processing": "true",
				"serverSide": "true",
				"ajax": {
					"url": "/admin/product/findAllAjax",
					"type": "POST"
				}
			 })
    });
JS;
$this->inlinescript()->captureEnd();
