<div class="content-wrapper">
	<section class="content-header">
		<h1>Products</h1>
		<ol class="breadcrumb">
			<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		</ol>
	</section>
	<section class="content">
		<div class="row">
			<div class="col-md-12">
				<div class="box box-primary">
					<div class="box-body">
                        <?php
                        $this->filter->prepare();
                        echo $this->form()->openTag($this->filter);
                        ?>
						<div class="col-md-3">
							<div class="form-group">
								<label>Program</label>
								<?php echo $this->formrow($this->filter->get('feed')); ?>
							</div>
						</div>
                        <?php
                        echo $this->form()->closeTag();
                        ?>
					</div>
				</div>
			</div>
		</div>
		<div class="box">
			<div class="box-body">
				<!-- 				<div class="grid-stack"> -->
				
					<?php
    // $dataGsX = 0;
    // $dataGsY = 0;
    
    // $dataGsWidth = 4;
    // $dataGsHeight = 4;
    
    // foreach ($this->paginator as $key => $entity) {
    // $key += 1;
    
    // echo '
    // <div class="grid-stack-item" data-gs-x="' . $dataGsX . '" data-gs-y="' . $dataGsY . '"
    // data-gs-width="' . $dataGsWidth . '" data-gs-height="' . $dataGsHeight . '">
    // <div class="grid-stack-item-content">Test</div>
    // </div>
    // ';
    
    // $dataGsX += 4;
    
    // if ($key % 3 == 0) {
    // $dataGsX = 0;
    // $dataGsY += 4;
    // }
    // }
    // ?>
<!-- 				</div> -->
				<table
					class="table table-striped table-hover table-condensed no-margin table-responsive">
					<thead>
						<tr>
							<th></th>
							<th>Unique ID</th>
							<th>Program ID</th>
							<th>Category</th>
							<th>Name</th>
						</tr>
					</thead>
					<tfoot>
						<tr>
							<th></th>
							<th>Unique ID</th>
							<th>Program ID</th>
							<th>Category</th>
							<th>Name</th>
						</tr>
					</tfoot>
				</table>
			</div>
		</div>
	</section>
</div>

<style type="text/css">
.grid-stack-item-content {
	padding: 5px;
	box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0
		rgba(0, 0, 0, 0.19);
}
</style>

<?php
$this->inlinescript()->captureStart();
echo <<<JS
    $(document).ready(function() {
//         var options = {
//             alwaysShowResizeHandle: /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent),
//             resizable: {
//                 handles: 'e, se, s, sw, w'
//             }
//         };

//         $('.grid-stack').gridstack(options);

        $('select').select2({allowClear: true, placeholder: 'Maak uw keuze'});

        $('table').DataTable({
            "processing": true,
            "serverSide": true,
            "ajax": {
                "url": "/admin/product/findAllAjax",
                "type": "POST",
                "data": function(d) {
                    d.filter = filter();
                }
            }
        });

        $('#filter :input:not(:button)').change(function(e) {
            e.preventDefault();

            $('table').DataTable().ajax.reload();
        });
    });

    function filter() {
        var filter = [];

        $('#filter :input:not(:button)').each(function() {
            filter.push({
                name: $(this).prop('name'),
                value: $(this).val()
            });
        });

        return filter;
    }
JS;
$this->inlinescript()->captureEnd();
