<div class="content-wrapper" style="min-height: 916px;">
	<!-- Content Header (Page header) -->
	<section class="content-header">
		<h1>
			Dashboard
		</h1>
		<ol class="breadcrumb">
			<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
			<li class="active">Dashboard</li>
		</ol>
	</section>

	<!-- Main content -->
	<section class="content">


		<!-- Main row -->
		<div class="row">

			<div class="col-md-8">
				<div class="box box-info">
            <div class="box-header with-border">
              <h3 class="box-title">Programs</h3>

              <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <div class="table-responsive">
                <table class="table no-margin">
                  <thead>
                  <tr>
                    <th>Program ID</th>
                    <th>Name</th>
                  </tr>
                  </thead>
                  <tbody>
                  <tr>
                    <td><a href="pages/examples/invoice.html">1723</a></td>
                    <td>LampenTotaal</td>
                  </tr>
                  </tbody>
                </table>
              </div>
              <!-- /.table-responsive -->
            </div>
            <!-- /.box-body -->
            <!-- <div class="box-footer clearfix">
              <a href="javascript:void(0)" class="btn btn-sm btn-info btn-flat pull-left">Place New Order</a>
              <a href="javascript:void(0)" class="btn btn-sm btn-default btn-flat pull-right">View All Orders</a>
            </div> -->
            <!-- /.box-footer -->
          </div>
			</div>

			<!-- Left col -->
			<div class="col-md-4">
				<!-- MAP & BOX PANE -->


				<!-- TABLE: LATEST ORDERS -->
				<div class="box box-info">
					<div class="box-header with-border">
						<h3 class="box-title">Websites</h3>

						<div class="box-tools pull-right">
							<button type="button" class="btn btn-box-tool"
								data-widget="collapse">
								<i class="fa fa-minus"></i>
							</button>
							<button type="button" class="btn btn-box-tool"
								data-widget="remove">
								<i class="fa fa-times"></i>
							</button>
						</div>
					</div>
					<!-- /.box-header -->
					<div class="box-body">
						<div class="table-responsive">
							<table class="table no-margin">
								<thead>
									<tr>
										<th>Website ID</th>
										<th>Name</th>
										<th>Status</th>
										<th>Actions</th>
									</tr>
								</thead>
								<tbody>
									<?php
									foreach($this->websites as $website) {
									    echo '
                                            <tr>
                                                <td>' . $website->getId() . '</td>
                                                <td>' . $website->getName() . '</td>
                                                <td><span class="label label-success">' . $website->getStatus() . '</span></td>
                                                <td>
    <div class="btn-group">
      <button type="button" class="btn btn-xs btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Choose action <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li><a href="/admin/object/1">View assigned objects</a></li>
        <li><a href="#">Another action</a></li>
        <li><a href="#">Something else here</a></li>
        <li role="separator" class="divider"></li>
        <li><a style="color: red;" href="#">Disable</a></li>
      </ul>
    </div>
                                                </td>
                                            </tr>
                                        ';
									}
									?>
								</tbody>
							</table>
						</div>
						<!-- /.table-responsive -->
					</div>
					<!-- /.box-body -->
					<div class="box-footer clearfix">

					</div>
					<!-- /.box-footer -->
				</div>
				<!-- /.box -->
			</div>
		</div>
		<!-- /.row -->

	</section>
	<!-- /.content -->
</div>

<?php
$this->inlinescript()->captureStart();
echo <<<JS
    $(document).ready(function() {
        $('.select2').select2();
    });
JS;
$this->inlinescript()->captureEnd();