<div class="content-wrapper">
	<section class="content-header">
		<h1><?php echo $this->translate('Search results'); ?></h1>
		<ol class="breadcrumb">
			<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		</ol>
	</section>
	<section class="content">
		<div class="box">
			<div class="box-body">
				<table
					class="table table-striped table-hover table-condensed no-margin">
					<thead>
						<tr>
							<th></th>
							<th>ID</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
                        <?php
                        if (! empty($this->data) && is_array($this->data)) {
                            
                            // echo '<pre>';
                            // \Doctrine\Common\Util\Debug::dump($this->data['hits'], 8);
                            // die();
                            
                            foreach ($this->data['suggest']['song-suggest'][0]['options'] as $options) {
                                echo '
                                    <tr>
                                        <td>
                                            <div class="btn-group">
                                                <button type="button" class="btn btn-xs btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    Choose action <span class="caret"></span>
                                                </button>
                                                <ul class="dropdown-menu">
                                                    <li role="separator" class="divider"></li>
                                                    <li><a style="color: red;" href="#">Disable</a></li>
                                                </ul>
                                            </div>
                                        </td>
                                        <td>' . $options['_id'] . '</td>
                                        <td>' . $options['text'] . '</td>
                                    </tr>
                                ';
                            }

                            if ((int) $this->data['hits']['total'] > 0) {
                                foreach ($this->data['hits']['hits'] as $hit) {
                                    echo '
                                        <tr>
                                            <td>
                                                <div class="btn-group">
                                                    <button type="button" class="btn btn-xs btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                        Choose action <span class="caret"></span>
                                                    </button>
                                                    <ul class="dropdown-menu">
                                                        <li role="separator" class="divider"></li>
                                                        <li><a style="color: red;" href="#">Disable</a></li>
                                                    </ul>
                                                </div>
                                            </td>
                                            <td>' . $hit['_id'] . '</td>
                                            <td>' . $hit['_source']['name'] . '</td>
                                        </tr>
                                    ';
                                }
                            }
                        }
                        ?>
                    </tbody>
					<tfoot>
						<tr>
							<th></th>
							<th>ID</th>
							<th></th>
						</tr>
					</tfoot>
				</table>
			</div>
		</div>
	</section>
</div>

<?php
$this->inlinescript()->captureStart();
echo <<<JS
    $(document).ready(function(){
       $('table').DataTable();
    })
JS;
$this->inlinescript()->captureEnd();